#!/bin/bash
ALIAS='extshark'
WEBROOT='/usr/share/'$ALIAS'/htdocs'
APACHECONF='/etc/apache2/conf-available/'$ALIAS'.conf'
ETC='/etc/'$ALIAS

echo $WEBROOT
echo $APACHECONF
echo $ETC

if [ $LOGNAME != "root" ]; then
        echo "Please run this script as root!"
        exit 1
fi


if [ ! -f $WEBROOT ]; then
	mkdir -p $WEBROOT
fi

if [ ! -f $ETC ]; then
	mkdir -p $ETC
fi

cp -rvf ./* $WEBROOT

printf "Alias /$ALIAS $WEBROOT

<DirectoryMatch ($WEBROOT)>
        Options FollowSymLinks

        DirectoryIndex index.php index.html

        AllowOverride AuthConfig
        Order Allow,Deny
        Allow From All

        AuthName \"extshark Access\"
        AuthType Basic
        AuthUserFile $ETC/htpasswd.users

        require valid-user
</DirectoryMatch>

<Directory $WEBROOT>
        Options +ExecCGI
</Directory>" > $APACHECONF

htpasswd -b -c $ETC/htpasswd.users admin password

cd /etc/apache2/conf-available
a2enconf $ALIAS

exit 0






